services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=Admin123
      - MINIO_DEFAULT_BUCKETS=bucket0
    networks:
      mynet:
        aliases:
          - my-localhost  # Alias for localhost access
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
networks:
  mynet:
    driver: bridge
volumes:
  minio_data:
    driver: local
