services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - "MSSQL_SA_PASSWORD=Admin123"
      - "ACCEPT_EULA=Y"
    ports:
      - 1433:1433
    volumes:
      - ./mssql_data:/var/opt/mssql/data
      - ./backups:/var/opt/mssql/backups
volumes: {}
