FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["SmallEnergy/SmallEnergy.csproj", "./SmallEnergy/"]
COPY ["AccesPoint/AccesPoint.csproj", "./AccesPoint/"]
RUN dotnet restore "./SmallEnergy/SmallEnergy.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "./SmallEnergy/SmallEnergy.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./SmallEnergy/SmallEnergy.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmallEnergy.dll"]